### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#10]
Would it be possible to move the support to Py3? Streamlink requires it now with a urllib3 version dependency. Also would it be possible to add a config line for the save directory and a separate folder for inprogress recordings and finished ones?

**Comment by mtverlee** [comment]
Absolutely, I'm about to start working on moving support to Python 3. Feel free to submit a pull request if you want.

**Comment by mtverlee** [comment]
Done with commit: https://github.com/mtverlee/lars/commit/018e224fc39402568ee0d0baf0e8d6785dccfb45

**Comment by camjac251** [comment]
This is amazing, thank you
