### ISSUE TITLE
Streams don't record if there is an offline channel before an online one.

### ISSUE THREAD

**Issue by mtverlee** [mtverlee/lars#12]
I'm sure it's a silly logic error but I'm to tired to fix it right now.

**Comment by camjac251** [comment]
Are streams checked in an interval? Does the twitch api support webhooks or something similar where streams can be seen as going offline without a cron to check? Something similar to [https://gist.github.com/smiley/78c1c2a57d17a179a978a1438b389710](https://gist.github.com/smiley/78c1c2a57d17a179a978a1438b389710)

**Comment by mtverlee** [comment]
They are checked on an interval, currently 120 seconds so as to not be rate-limited by the Twitch API. Not sure about webhooks, that is a good idea though. This bug is fixed with [this commit](aec2f435f8ab18e5a630a5884cd807fcb2468792), so this issue is marked as fixed. Creating an issue [here](https://github.com/mtverlee/lars/issues/13) for the webhooks.
