### ISSUE TITLE
Symbols in filename result in save error

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#17]
I noticed that in my log, some stream titles have symbols that are not allowed Unix/Windows. When that happens, the file fails to write it seems

I see this in my log
```
error: Failed to open output: /streams/recording/[trainwreckstv](2019-04-11_06:52)<Finishing Season 2 TWD --- Moving Sub night to Saturday | twitter.com/trainwreckstv>.mp4 ([Errno 2] No such file or directory: '/streams/recording/[trainwreckstv](2019-04-11_06:52)<Finishing Season 2 TWD --- Moving Sub night to Saturday | twitter.com/trainwreckstv>.mp4')
[cli][info] Closing currently open stream...
```

Would it be possible to replace illegal characters with dashes? Or write the full metadata as a text file instead and the filename would just be channel - date? I think I've seen the filenames change when the stream title did, not sure.

**Comment by mtverlee** [comment]
This should be fixed in [this](url) commit. I'll look into removing the illegal characters but for now I've just reverted to use ```file_name = '[' + channel + '](' + time + ').mp4'``` instead so we avoid the stream title completely.
