### ISSUE TITLE
Lock files aren't deleted

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#19]
I noticed another critical bug with lars. When a stream ends, the lock file that was made isn't deleted after the stream is over, so if the stream restarts then it won't get recorded. In the log it shows that the channel is already recording even though a streamlink process for it isn't up and the lockfile still exists.

**Comment by mtverlee** [comment]
This issue should be fixed as of version 2.0 ([info](https://github.com/mtverlee/lars/commit/e6f3d1fa087b96ca1d7371125f42c38e7b39005c)). Lars no longer uses lock files and instead now uses a small local database. This breaks backwards compatibility and you will need to reinstall.

Apologies for taking so long. :)
