### ISSUE TITLE
Livestreamer outdated (streamlink fork)

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#5]
I wanted to let you know about https://github.com/streamlink/streamlink

It went up around the time twitch started requiring authentication for watching streams, and fixes a lot of things that livestreamer still suffers with. Would be cool to use this over livestreamer for this script.

**Comment by mtverlee** [comment]
That looks great! I didn't realize that streamlink existed. :) I'll take a look at creating a fork for it!

**Comment by mtverlee** [comment]
Done with commit: https://github.com/mtverlee/lars/commit/018e224fc39402568ee0d0baf0e8d6785dccfb45
